### ISSUE TITLE
Is this being maintained?

### ISSUE THREAD

**Issue by dpshelio** [healpy/cfitsio#3]
Is this the "official" upstream for cfitsio? It seems outdated with [cfitsio](https://heasarc.gsfc.nasa.gov/fitsio/fitsio.html) heasarc's page. I've not found other repository where cfitsio is being developed.

**Comment by zonca** [comment]
No, it is not, it is just a copy of the .tar.gz archives released by heasarc

Il mer 8 nov 2017, 14:28 David Pérez-Suárez <notifications@github.com> ha
scritto:
