### ISSUE TITLE
make[1]: Entering directory 

### ISSUE THREAD

**Issue by Hamza757** [healpy/cfitsio#6]
Hi,
 I tried to compile cfitsio with the command make but I got the following result: 

make[1]: Entering directory '/home/hamza/cfitsio-3.47'
make[1]: Nothing to be done for 'stand_alone'.
make[1]: Leaving directory '/home/hamza/cfitsio-3.47'

Please, I need help to solve this problem
Hamza

**Comment by zonca** [comment]
have you run `./configure`?
please look at the documentation https://heasarc.gsfc.nasa.gov/docs/software/fitsio/quick/node3.html
